rungalileo/galileo-python

src/galileo/decorator.py
src/galileo/utils/singleton.py

How to test:
```
@log
def _call_llm_galileo(messages: list[dict]) -> str:
client = OpenAI()
response = client.chat.completions.create(model="gpt-4o", messages=messages)
return response.choices[0].message.content
messages = [{"role": "user", "content": "Hey bot"}]
c = _call_llm_galileo(messages)
print("run 1", c)
inputs = [{"messages": messages} for _ in range(2)]
with ThreadPoolExecutor(max_workers=1) as executor:
futures = [
executor.submit(_call_llm_galileo, **input_) for input_ in inputs
]
contents = []
for future in as_completed(futures):
c = future.result()
contents.append(c)
print("run 2", contents)
```
> Note: to understand the change I recommend to enable DEBUG logs (for galileo):
```
LOGGING_CONFIG = {
"version": 1,
"handlers": {
"default": {
"class": "logging.StreamHandler", …
```

feat: use @log with ThreadPoolExecutor

---

src/galileo/openai.py
tests/test_openai.py

resolves https://app.shortcut.com/galileo/story/26598/qa2-0-logstreams-metrics-status-code-is-0-instead-of-200-for-successful-run

fix: Set correct openai status code for successful run

---

src/galileo/prompts.py
src/galileo/utils/exceptions.py
tests/test_prompts.py

This PR fixes https://app.shortcut.com/galileo/story/26778/typeerror-exceptions-must-derive-from-baseexception-in-python-client
How to test:
run create_prompt_template 2 times
```
tmpl = create_prompt_template(
name="andrii-good-prompt1111",
project="andrii-new-project",
messages=[Message(role=MessageRole.SYSTEM, content="you are a helpful assistant"), Message(role=MessageRole.USER, content="why is sky blue?")]
)
tmpl = create_prompt_template(
name="andrii-good-prompt1111",
project="andrii-new-project",
messages=[Message(role=MessageRole.SYSTEM, content="you are a helpful assistant"), Message(role=MessageRole.USER, content="why is sky blue?")]
)
```
output:
```
python /Users/andrii/work/rungalileo/galileo-python/downloads/promt_template.py 
Traceback (most recent call last):
File …
```

fix: improve error handling and print better error when create prompt template fails

---

src/galileo/experiments.py
tests/test_experiments.py

This PR improves error handling of:
```
results = run_experiment(
"travel-experiment",
dataset=get_dataset(name="travel-durations"),
prompt_template=prompt_template,
prompt_settings={
"model_alias": "GPT-4o",
},
project=project_name,
metrics=["Sentence Density"],
)
```
and Experiments.get api returns None:
```
Traceback (most recent call last):
File "/Users/pawandeshpande/dev/sdk-demo-streamlit/experiment.py", line 52, in <module>
results = run_experiment(
^^^^^^^^^^^^^^^
File "/Users/pawandeshpande/dev/sdk-demo-streamlit/env/lib/python3.12/site-packages/galileo/experiments.py", line 235, in run_experiment
experiment_obj = Experiments().get_or_create(project_obj.id, experiment_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

fix: Ierror handling in Experiments.get

---

README.md
src/galileo/prompts.py
tests/test_prompts.py

[Shortcut #27505: Standardize the message role enum](https://app.shortcut.com/galileo/story/27505/g2-0-python-sdk-standardize-the-messagerole-models)
Searching [github](https://github.com/search?q=org%3Arungalileo+%2F%28%3F-i%29MessageRole%5C.%2F&type=code) for `MessageRole` enum indicates that all repositories apart from this use lower casing for this enum. So, we are going to lower case this enum and its usages to be consistent across the board.

chore: Enum name normalization

---

src/galileo/datasets.py
tests/test_datasets.py
tests/test_openai_agents.py

This PR resolves https://app.shortcut.com/galileo/story/26711/g2-0-python-sdk-add-dataset-version-methods
It adds 2 functions:
* `get_dataset_version_history(dataset_name=None, dataset_id=None)` returns a list of `DatasetVersion` (after calling `/datasets/{dataset_id}/versions/query` api ;
* `get_dataset_version(dataset_name=None, dataset_id=None, version_index)` - returns and loads if calling from the `Dataset` object the DatasetContent for the specific version (after calling `/datasets/{dataset_id}/versions/{version_index}/content` api.

feat: add dataset version methods

---

README.md
src/galileo/__init__.py
src/galileo/prompts.py
src/galileo/schema/message.py
src/galileo/schema/message_role.py
tests/schemas/test_message.py
tests/test_decorator.py
tests/test_langchain.py
tests/test_langchain_async.py
tests/test_openai.py
tests/test_prompts.py

Following PR does the following according to the detailed discussion which happened [here](https://galileoteamworkspace.slack.com/archives/C087G0X1JG2/p1744123147608439)
1. Adds wrapper classes for `Message` and `MessageRole` within python SDK which internally inherits from `galileo_core`. This is done to ensure name, functionality normalization across the board [27505](https://app.shortcut.com/galileo/story/27505/g2-0-python-sdk-standardize-the-messagerole-models)
2. Exposes the new class (along with its component classes) right at the package level so that they can be imported as `from galileo import Message, MessageRole, ToolCall, ToolCallFunction`. This is done to ensure `galileo_core` remains encapsulated and also to prevent confusion of importing from different packages/sources.
3. …

fix: Use `Message` and `MessageRole` models from `galileo-core`

---

src/galileo/experiments.py
tests/test_experiments.py

Resolves https://app.shortcut.com/galileo/story/27772/python-sdk-no-error-if-unknown-metrics-specified-in-experiments
Run this sample:
```
import logging
import os
from random import choice
from string import ascii_letters
from galileo.datasets import create_dataset
from galileo.experiments import run_experiment
from galileo.projects import create_project
from galileo.prompts import create_prompt_template
from galileo.resources.models import Message, MessageRole
suffix=''.join(choice(ascii_letters) for _ in range(6))
project = f"My first project {suffix}"
create_project(project)
os.environ["GALILEO_PROJECT"] = project
prompt_template = create_prompt_template(
name=f"storyteller-prompt-{suffix}",
project=project,
messages=[
Message(role=MessageRole.SYSTEM, content="You are a great …
```

feat: error if a non existent metric is specified

---

src/galileo/datasets.py
tests/test_datasets.py
tests/test_experiments.py

This PR solves https://app.shortcut.com/galileo/story/26791/g2-0-python-and-ts-sdks-json-datasets-are-not-being-passed-into-runner-functions-correctly
Create JSON like dataset
```
test_data = [
{
"question": "Which continent is Spain in?",
"expected": "Europe",
},
{
"question": "Which continent is Japan in?",
"expected": "Asia",
},
]
dataset = create_dataset(
"storyteller-dataset1",
test_data,
)
```
Run an experiment with local runner and this dataset:
```
def runner(input):
return openai.chat.completions.create(
model="gpt-4o",
messages=[
{"role": "user", "content": f"Say hello: {input['question']}"}
],
).choices[0].message.content
run_experiment(
"test experiment runner10",
project="andrii-new-project",
dataset=get_dataset(name="storyteller-dataset1"),
function=runner, …
```

fix: JSON datasets are not being passed into runner functions correctly

---

src/galileo/handlers/langchain/async_handler.py
src/galileo/handlers/langchain/handler.py
tests/test_langchain.py
tests/test_langchain_async.py

Few fixes:
1. `on_retriever_start` wasn't working correctly bc it was missing a positional argument (`serialized`).
2. `on_tool_end` was serializing unnecessary Langchain metadata as the output when we only care about the `content` (if it exists in the object). This was originally suggested by a user (@ChrisTague1) in the following PR: https://github.com/rungalileo/galileo-python/pull/90 . Since the tool output is typed as Any and Langchain doesn't have proper documentation for what to expect, I'm doing some type checking and handling.
3. In async streaming scenarios, `on_chain_start `actually sends an empty string as the input and then sends the full input in `on_chain_end`. Updating the async handler to reflect this.

fix: Updating the Langchain handler retriever, tool, async chain callbacks

---

src/galileo/datasets.py
tests/test_datasets.py

[sc-28511](https://app.shortcut.com/galileo/story/28511/add-rows-to-dataset-through-python-sdk-not-working) : Add rows to dataset through python sdk not working.
We were using `DatasetUpdateRow` which targets updating a specific row instead of adding new rows to the dataset. We should be using `DatasetAppendRow` to achieve the same which this PR adds. 
We also add test to verify we are using the right dataset entity for adding new rows.

fix: Fix functionality to add new rows to dataset

---

src/galileo/openai.py
tests/test_openai.py

https://app.shortcut.com/galileo/story/28964/openai-wrapper-can-t-append-llm-node-to-existing-trace
This will allow users to create a single trace with multiple LLM spans generated by our OpenAI client wrapper (without using the `log` decorator):
```
client = openai.OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
logger = galileo_context.get_logger_instance()
logger.start_trace("test trace")
client.chat.completions.create(messages=[{"role": "user", "content": "Say this is a test"}], model="gpt-4o-mini")
client.chat.completions.create(
messages=[{"role": "user", "content": "Say this is a second test"}], model="gpt-4o-mini"
)
logger.conclude(output="trace completed")
logger.flush()
```

fix: Fixing the OpenAI wrapper when it's used in an active trace

---

src/galileo/constants/routes.py
src/galileo/decorator.py
src/galileo/logger.py
src/galileo/schema/trace.py
src/galileo/utils/core_api_client.py
tests/test_decorator.py
tests/test_logger.py
tests/testutils/setup.py

Adding session management to the GalileoLogger
```
logger.start_session(name="test-session", previous_session_id="6c4e3f7e-4a9a-4e7e-8c1f-3a9a3a9a3a9e", external_id="myAppId123")
...
logger.clear_session()
```
https://app.shortcut.com/galileo/story/29394/sdk-add-session-compatibility-to-the-galileologger-python

feat: Session management

---

src/galileo/decorator.py
tests/test_galileo_context.py

The previous change (https://github.com/rungalileo/galileo-python/pull/126) was causing the project and log stream to get set to "default" in the decorator, and these values were being passed to the GalileoLogger init method. Project and Log Stream defaults should be set by GalileoLogger.

fix: Reverting a change from a previous context manager fix

---

src/galileo/datasets.py
tests/test_datasets.py

This PR resolves issues with [creating empty datasets for example:](https://app.shortcut.com/galileo/story/28509/create-dataset-python-sdk-creating-empty-dataset-not-working)
🟢  OK
```
dataset = create_dataset(
name = "countries",
content=[],
)
```
🟢  OK
```
dataset = create_dataset(
name = "countries",
content={},
)
```
🔴 FAIL `ValueError`
```
dataset = create_dataset(
name = "countries",
content=None,
)
```

fix: creating empty dataset

---

src/galileo/logger.py
tests/test_logger.py

This changes the `start_session` function to return the session ID, and adds a new `set_session` function.

feat: Enable setting session ID

---

src/galileo/handlers/langchain/async_handler.py
src/galileo/handlers/langchain/handler.py
tests/test_langchain.py
tests/test_langchain_async.py

https://app.shortcut.com/galileo/story/32021/langgraph-provide-the-timestamp-at-which-each-span-starts-getting-executed

fix: Making sure that created_at is set during node creation for Langchain

---

.github/workflows/publish-docs.yaml

Running this action in GH fails as the `__init__.mdx` files are now removed by a clean up step. Removing this delete.

fix: removing failiing delete call that's not needed

---

src/galileo/handlers/langchain/async_handler.py
src/galileo/handlers/langchain/handler.py
tests/test_langchain.py
tests/test_langchain_async.py

With this change - the Aggregated Graph view distinguishes the two agents separately

fix: Fixed langchain handler to include parent info in agent node names

---

src/galileo/prompts.py
tests/test_prompts.py

**Shortcut:** 
https://app.shortcut.com/galileo/story/35027/python-sdk-add-pending-prompt-functionality
**Description:**  
This PR adds new SDK utilities for updating **global** prompt templates. All functions operate at the global level and do not require a project name.
---
Updates a **global** prompt template by either ID or existing name.
- You **must** provide either `id` or `name` (but not both) to identify the template to update.
- You **must** provide `new_name` with the updated template name.
- Returns the updated template object.
**Parameters:**
| Name       | Type     | Description                                           |
|------------|----------|-------------------------------------------------------|
| `id`       | `string` | The unique identifier of the template to update …

feat: Add update prompt functionality

---

poetry.lock
src/galileo/logger/batch.py
src/galileo/logger/interface.py
src/galileo/logger/logger.py
tests/test_logger.py

Shortcut:
galileo python Support ingesting redacted [sc-34867]
Description:
Adds support for redacted fields for spans in traces logger
Tests:

feat: Support ingesting redacted input and output fields

---

src/galileo/prompts.py
tests/test_prompts.py

**Shortcut:** 
https://app.shortcut.com/galileo/story/35027/python-sdk-add-pending-prompt-functionality
**Description:**  
Renders a **global** prompt template with provided data and returns the rendered results.
- You **must** provide a `template` string to render.
- You **must** provide `data` for template rendering (supports multiple formats).
- Supports pagination with `starting_token` and `limit` parameters.
**Parameters:**
| Name             | Type                                           | Description                                                    |
|------------------|------------------------------------------------|----------------------------------------------------------------|
| `template`       | `string`                                       | The template string to …

feat: Add render prompt functionality

---

src/galileo/logger/logger.py
tests/conftest.py
tests/test_logger_streaming.py

Move `mode` out of the GalileoLogger constructor and swap with `experimental` until streaming mode is ready for prime time.
usage:
```
logger = GalileoLogger(experimental={"mode": "experimental"})
```

feat: move `mode` to an experimental param

---

src/galileo/__init__.py
src/galileo/handlers/langchain/async_handler.py
src/galileo/handlers/langchain/handler.py
src/galileo/utils/serialization.py
tests/test_langchain.py
tests/test_langchain_async.py

I was looking over some recent logstreams created with Langchain/Langgraph today, and noticed that a lot of them contained "raw Langchain" data in span inputs and/or outputs.
E.g. LLM messages that have `"content"` as a dict with its own inner "content" key, plus a dict called "additional_kwargs," and all of that stuff.  And we often weren't setting our own schema's `tool_call_id` either on tool nodes or on the LLM output messages that called the tools.
----
This PR updates our langchain callbacks to fix at least some of the problems I observed.
I tested this against the [langgraph-fsi-agent](https://github.com/rungalileo/sdk-examples/tree/main/python/agent/langgraph-fsi-agent) example from our SDK examples repo, and I can confirm it works in that case, although I can't guarantee it works …

fix: Make langchain callbacks produce data closer to our schema's intentions

---

src/galileo/decorator.py
src/galileo/utils/singleton.py

Removing `mode` from galileo_context until streaming mode is ready to be exposed

fix: removing `mode` from galileo_context

---

codegen_templates/endpoint_macros.py.jinja
codegen_templates/endpoint_module.py.jinja
codegen_templates/property_templates/model_property.py.jinja

**shortcut:** https://app.shortcut.com/galileo/story/34869/galileo-python-migrate-all-api-interactions-to-use-config-and-api-client-from-galileo-core#activity-36213
**description:** This adds the default openapi-autogen [templates](https://github.com/openapi-generators/openapi-python-client/tree/main/openapi_python_client/templates) needed for the api resources. This is just to allow for a proper diff against [254](https://github.com/rungalileo/galileo-python/pull/254) which has the template changes.

chore: Add the default templates for openapi-autogen endpoint resources

---

src/galileo/logger/logger.py
src/galileo/utils/core_api_client.py
tests/test_logger_batch.py
tests/test_logger_streaming.py

Adding the ability to log a protect call using `add_protect_span` in the GalileoLogger. This is basically a port from 1.0 where a Tool span is created using the serialized payload and response.
https://app.shortcut.com/galileo/story/36673/add-protect-log-functionality-to-our-logger

feat: logging for Protect calls

---

poetry.lock
pyproject.toml
src/galileo/handlers/crewai/__init__.py
src/galileo/handlers/crewai/handler.py
tests/test_crewai_handler.py

Updates the Galileo Python SDK's CrewAI integration to support CrewAI version 0.159.0 and above by fixing UUID handling compatibility issues.
Fixed UUID handling: Added _to_uuid() helper method to safely handle both UUID objects and strings
Removed version cap: Updated dependency from >=0.152.0,<0.153.0 to >=0.152.0
Updated tests: Added parametrized tests for both UUID and string scenarios
```
[EventBus Error] Handler 'on_llm_call_started' failed for event 'LLMCallStartedEvent': 'UUID' object has no attribute 'replace'
```
CrewAI 0.159.0+ changed how IDs are passed to event handlers (UUID objects vs strings), causing the handler to fail. This fix maintains compatibility with both old and new versions.
✅ Backward compatible
✅ Supports latest CrewAI versions
✅ No breaking changes …

feat: update handler to support crew ai 0.159.0

---

src/galileo/config.py
tests/test_config.py

**shortcut:** https://app.shortcut.com/galileo/story/39176/galileo-console-url-not-defaulting-to-plg [sc-39176]
**description:** GALILEO_CONSOLE_URL not defaulting to PLG cluster

fix: Set a default console url

---

src/galileo/experiments.py
src/galileo/projects.py
src/galileo/stages.py
tests/test_experiments.py
tests/test_projects.py
tests/test_stages.py

The `run_experiment` function expects a project name. To make this more consistent with other functions, this change adds the ability to:
- Pass in a project by Id (the other experiment functions only take the Id)
- Not pass in a project and have it loaded from an environment variable
[SC-40118](https://app.shortcut.com/galileo/story/40118/run-experiment-should-support-project-ids-and-projects-from-env-vars)

chore: Adding support for loading  projects from env vars in experiments

---

src/galileo/projects.py
tests/test_stages.py

Previously the code was setting both `id` and `name`, backfilled from the env vars. This was causing an issue when, for ex, project_id was passed but the GALILEO_PROJECT env var was set.

fix: updating `get_with_env_fallbacks` to not set/pass both id and name

---

poetry.lock
pyproject.toml
src/galileo/handlers/crewai/handler.py
src/galileo/handlers/langchain/utils.py

This PR implements support for CrewAI version [0.186.1](https://github.com/crewAIInc/crewAI/releases/tag/0.186.1) and includes a bug fix for LangChain agent detection.
- Updated CrewAI dependency version constraint from >=0.152.0,<0.160.0 to >=0.152.0,<=0.186.1
- Updated project optional dependencies to support CrewAI up to version 0.186.1
- Updated poetry.lock with new dependency versions
- LangChain Agent Detection: Improved agent node detection by making the comparison case-insensitive (node_name.lower() in ["langgraph", "agent"])
- Ensures backward compatibility with existing CrewAI versions
- Maintains proper agent detection for LangChain integrations
Addresses ticket SC-40330

feat: Implement support for crewai version 0.186.1

---

src/galileo/scorers.py
tests/test_scorers.py

**shortcut:** https://app.shortcut.com/galileo/story/42082/do-tool-metrics-not-working-on-experiments [sc-42082]
**description:** List scorers endpoint is paginated but the call to it is not handling the pagination.

feat: Paginate list scorers

---

src/galileo/projects.py
tests/test_projects.py

**shortcut:** https://app.shortcut.com/galileo/story/42295/verizon-2-0-workflow-for-updating-user-permissions-on-projects#activity-42428 [sc-42428]
**description:** Support workflow for updating user permissions on projects
Verizon has workflows that require listing out projects, viewing all users those projects are shared with, and updating those permissions based on their changing org structure and company.

feat: Add project user management methods

---

src/galileo/export.py
tests/test_export.py

**shortcut:** https://app.shortcut.com/galileo/story/42678/update-the-export-library
**description:** Set default values for sort, filter and root_type for export_records. The API already sets default for sort and filter but for some reason the generated resources for these aren't optional and have no defaults so we set them to the server defaults. Additionally we set a default for root_type since it's required, and we default to the oldest logstream if no ids are provided.

feat: Set default values for export_records

---

src/galileo/metrics.py
src/galileo/scorers.py
tests/test_metrics.py
tests/test_scorers.py

**shortcut:** https://app.shortcut.com/galileo/story/40920/python-sdk-no-way-to-delete-a-metric [sc-40920]
**description:** No way to delete a metric in python SDK

feat: Delete metric
